import {describe,it,expect} from 'vitest';
import {extractSources,normalizeResult,inputSchema,safeUrl,reconcileMaterials} from './estimate.mjs';
const sources=[{id:'S1',url:'https://supplier.example/product',title:'Material'}];
const result=()=>({summary:'Test scope',items:[{description:'Floor material',category:'material',quantity:10,unit:'each',unitCost:30,laborHours:0,hourlyRate:0,basis:'listed-price',sourceIds:['S1'],rationale:'10 boxes at published unit price.'}],materials:[{itemIndex:0,product:'Flooring box',supplier:'Supplier',location:'Harrisburg',preference:'local',availability:'Verify stock',sourceId:'S1'}],benchmarks:[],assumptions:[],exclusions:[],questions:[],researchGaps:[]});
describe('estimate evidence validation',()=>{
 it('assigns shopping list indices from nested cost lines without model cross-references',()=>{const r=result();const {itemIndex,...material}=r.materials[0];const raw={...r,items:[{description:'Install',category:'labor',quantity:1,unit:'allowance',unitCost:0,laborHours:8,hourlyRate:60,basis:'estimated-allowance',sourceIds:[],rationale:'Allowance',material:null},{...r.items[0],material}]};const normalized=normalizeResult(reconcileMaterials(raw),sources);expect(normalized.materials[0].itemIndex).toBe(1);expect(normalized.items[1].description).toBe('Floor material');});
 it('labels missing suppliers unverified and rejects suppliers attached to labor',()=>{const r=result();expect(reconcileMaterials({...r,items:[{...r.items[0],material:null}]}).materials[0].preference).toBe('unverified');expect(()=>reconcileMaterials({...r,items:[{...r.items[0],category:'labor',material:r.materials[0]}]})).toThrow();});
 it('accepts priced materials reconciled to the estimate',()=>expect(normalizeResult(result(),sources).materials).toHaveLength(1));
 it('does not present a general guide as a verified whole-project comparison',()=>{const r=result();r.benchmarks=[{label:'Guide',kind:'cost-guide',location:'PA',low:4,high:10,unit:'sq ft',projectArea:null,scopeMatch:'whole-project',sourceId:'S1',notes:'Installation guide'}];expect(normalizeResult(r,sources).benchmarks[0].scopeMatch).toBe('context-only');});
 it('labels uncited supplier suggestions as unverified',()=>{const r=result();r.materials[0].sourceId=null;const n=normalizeResult(r,sources);expect(n.materials[0].preference).toBe('unverified');expect(n.researchGaps.some(g=>g.includes('Supplier evidence'))).toBe(true);});
 it('rejects fabricated source IDs and unsourced price claims',()=>{const r=result();r.items[0].sourceIds=['S99'];expect(()=>normalizeResult(r,sources)).toThrow();r.items[0].sourceIds=[];expect(()=>normalizeResult(r,sources)).toThrow();});
 it('rejects missing or duplicated material mappings',()=>{const r=result();r.materials=[];expect(()=>normalizeResult(r,sources)).toThrow();const d=result();d.materials.push({...d.materials[0]});expect(()=>normalizeResult(d,sources)).toThrow();});
 it('rejects duplicate labor charges and reversed comparison ranges',()=>{const r=result();r.items[0].laborHours=10;expect(()=>normalizeResult(r,sources)).toThrow();const b=result();b.benchmarks=[{label:'Guide',kind:'cost-guide',location:'PA',low:50,high:10,unit:'sq ft',projectArea:null,scopeMatch:'whole-project',sourceId:'S1',notes:''}];expect(()=>normalizeResult(b,sources)).toThrow();});
 it('extracts only real citation URLs and rejects unsafe schemes/local links',()=>{const response={output:[{type:'message',content:[{annotations:[{type:'url_citation',url:'https://supplier.example/product',title:'Product'},{type:'url_citation',url:'javascript:alert(1)'},{type:'url_citation',url:'http://127.0.0.1/secret'}]}]}]};expect(extractSources(response)).toEqual([{id:'S1',url:'https://supplier.example/product',title:'Product'}]);expect(safeUrl('https://user:password@example.com')).toBeNull();});
 it('rejects negative or nonfinite job pricing and unreasonable payloads',()=>{expect(inputSchema.safeParse({type:'roofing',answers:{address:'Harrisburg'},pricing:{laborRate:-1,markup:15,tax:0,contingency:0},area:100}).success).toBe(false);});
 it('never uses forum anecdotes as market benchmarks',()=>{const r=result();const forum=[...sources,{id:'S2',url:'https://www.reddit.com/r/Flooring/example',title:'Anonymous post'}];r.benchmarks=[{label:'Project',kind:'cost-guide',location:'PA',low:4,high:10,unit:'sq ft',projectArea:null,scopeMatch:'whole-project',sourceId:'S2',notes:''}];expect(normalizeResult(r,forum).benchmarks).toHaveLength(0);});
});
