import { useState } from 'react';
import { ExternalLink, Sparkles, RefreshCw, CircleAlert } from 'lucide-react';
import type { Quote } from './domain';
import { money, totals } from './domain';
import { comparisonRange, projectArea, evidenceChanged } from './ai';
import type { AIReport as Report } from './ai';
export function SourceLink({report,id}:{report:Report;id:string|null}){const s=report.sources.find(s=>s.id===id);return s?<a href={s.url} target="_blank" rel="noopener noreferrer" className="source-link">{s.title}<ExternalLink size={12}/></a>:<small className="fine-print">No verified price source</small>;}
export default function AIReport({quote,regenerate,update}:{quote:Quote;regenerate:()=>void;update:(p:Partial<Quote>)=>void}){
  const [tab,setTab]=useState<'summary'|'materials'|'comparison'>('summary');const report=quote.ai!;const area=projectArea(quote);const total=totals(quote.lines,quote.pricing).total;const ranges=comparisonRange(report);const low=ranges.length?Math.min(...ranges.map(r=>r.low)):null;const high=ranges.length?Math.max(...ranges.map(r=>r.high)):null;
  const scopeChanged=JSON.stringify({type:quote.type,answers:quote.answers,pricing:quote.pricing})!==report.fingerprint;
  return <section className="ai-report"><div className="ai-report-heading"><div><span className="ai-label"><Sparkles size={15}/>AI-prepared draft</span><h2>{report.summary}</h2><p>Researched {new Date(report.researchedAt).toLocaleDateString()} · {report.sources.length} cited sources · Review before approval</p></div><button className="secondary" onClick={regenerate}><RefreshCw size={15}/>Research again</button></div>{scopeChanged&&<p className="ai-notice"><CircleAlert size={16}/>Inputs or pricing settings changed since research. Review quantities and assumptions, or regenerate.</p>}<div className="research-tabs" role="group" aria-label="Estimate research">{(['summary','materials','comparison'] as const).map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='summary'?'Plan & assumptions':t==='materials'?'Material list':'Price comparison'}</button>)}</div>
  {tab==='summary'&&<div className="research-body"><div className="research-columns"><section><h3>What we allowed for</h3><ul>{report.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul></section><section><h3>What needs confirmation</h3>{!report.questions.length?<p>No extra questions were proposed. Review the measurements and allowances below.</p>:report.questions.map((question,i)=><label className="research-question" key={i}><input type="checkbox" checked={report.resolvedQuestions.includes(i)} onChange={e=>update({ai:{...report,resolvedQuestions:e.target.checked?[...report.resolvedQuestions,i]:report.resolvedQuestions.filter(n=>n!==i)}})}/><span>{question}<small>Mark resolved after updating the scope or estimate.</small></span></label>)}</section></div>{report.researchGaps.length>0&&<details className="research-gaps" open><summary>Research limitations</summary><ul>{report.researchGaps.map((g,i)=><li key={i}>{g}</li>)}</ul></details>}</div>}
  {tab==='materials'&&<div className="research-body"><p className="panel-help">Material costs are already included in the estimate below. Quantities reflect current line edits. Links are research sources, not confirmed orders or stock.</p>{!report.materials.length&&<p>No separate material purchases identified for this scope.</p>}{[...report.materials].sort((a,b)=>['local','online','unverified'].indexOf(a.preference)-['local','online','unverified'].indexOf(b.preference)).map(m=>{const line=quote.lines.find(l=>l.id===report.lineIds[m.itemIndex]);const item=report.items[m.itemIndex];return <article className="material-row" key={m.itemIndex}><div><span className={`supplier-label ${m.preference}`}>{m.preference==='local'?'Local source':m.preference==='online'?'Online source':'Source needs confirmation'}</span><h3>{m.product}</h3><p>{m.supplier} · {m.location}</p><small>{m.availability}</small><SourceLink report={report} id={m.sourceId}/></div><div className="material-cost">{line?<><strong>{line.quantity.toLocaleString()} {line.unit}</strong><span>{money(line.material)} / {line.unit}</span><b>{money(line.quantity*line.material)}</b></>:<strong>Removed from estimate</strong>}<small>{line&&evidenceChanged(line,item)?'Edited line — verify against original research':item.basis==='estimated-allowance'?'Estimated allowance — confirm price':'AI-read published price — verify at checkout'}</small></div><p className="material-rationale">{item.rationale}</p></article>;})}</div>}
  {tab==='comparison'&&<div className="research-body"><div className="benchmark-summary"><div><small>Your current quote</small><strong>{money(total)}</strong><span>{area?`${money(total/area)} / sq ft · ${Math.round(area).toLocaleString()} sq ft`:'Add a confirmed area for a square-foot comparison'}</span></div><div><small>Comparable published range</small><strong>{low!==null&&high!==null?`${money(low)}–${money(high)}`:'No reliable full-scope range'}</strong><span>{low!==null?'per sq ft · union of relevant published ranges':'Broader and component references may appear below.'}</span></div></div>{report.marketRange&&<div className="benchmark-summary"><div><small>Market low</small><strong>{money(report.marketRange.low)}</strong></div><div><small>Market mid — quote target</small><strong>{money((report.marketRange.low+report.marketRange.high)/2)}</strong></div><div><small>Market high</small><strong>{money(report.marketRange.high)}</strong></div><span>{report.marketRange.basis}</span></div>}<p className="panel-help">Your total includes configured markup, contingency, Project Fee and tax. Source prices may include different items. Comparisons are context, not proof of a competitor’s bid.</p>{report.benchmarks.map((b,i)=><article className="benchmark-row" key={i}><span className="supplier-label">{b.kind==='documented-project'?'Documented project':'Published cost guide'} · {b.scopeMatch.replaceAll('-',' ')}</span><h3>{b.label}</h3><p>{b.location}</p><strong>{money(b.low)}–{money(b.high)} {b.unit==='sq ft'?'/ sq ft':'total'}</strong><p>{b.notes}</p><SourceLink report={report} id={b.sourceId}/></article>)}{!report.benchmarks.length&&<p>No verifiable comparable prices were found. The app has not invented a market range.</p>}</div>}
  <details className="all-sources"><summary>View all research sources</summary>{report.sources.map(s=><SourceLink key={s.id} report={report} id={s.id}/>)}</details></section>;
}
