import { Building2, House, HardHat, ChevronRight, FileText, SlidersHorizontal, ArrowUpRight } from 'lucide-react';
import { useState } from 'react';
import { Footer } from './components';
import { jobNames, money, totals } from './domain';
import type { JobType, Quote } from './domain';
const descriptions = { renovation: 'Build-outs, interiors & multi-trade work', roofing: 'Repairs, replacements & roof systems', contracting: 'Custom scopes & specialty work' };
const icons = { renovation: Building2, roofing: House, contracting: HardHat };
export default function Home({ quotes, start, resume, settings }: { quotes: Quote[]; start: (t: JobType) => void; resume: (id: string) => void; settings: () => void }) {
  const [selected, select] = useState<JobType>('renovation');
  return <><main className="home-layout"><section className="start-panel"><div className="intro"><h1>What are we quoting?</h1><p>Choose the work. We’ll guide you from scope to price.</p></div><div className="job-options" role="group" aria-label="Job type">{(Object.keys(jobNames) as JobType[]).map(type => { const Icon = icons[type]; return <button key={type} className={`job-option ${selected === type ? 'selected' : ''}`} onClick={() => select(type)} aria-pressed={selected === type}><span className="job-icon"><Icon size={29} strokeWidth={1.5}/></span><span><strong>{jobNames[type]}</strong><small>{descriptions[type]}</small></span><ChevronRight size={22}/></button>; })}</div><button className="connection-link" onClick={settings}><SlidersHorizontal size={19}/><span>Pricing & connections<small>Your rates, preferences and connected services</small></span><ChevronRight size={18}/></button><div className="device-note">AI uses the job address and scope to research pricing. Quotes stay saved on this device.</div></section><section className="quotes-panel"><div className="section-heading"><h2>Your quotes</h2><span>{quotes.length}</span></div>{quotes.length === 0 ? <div className="empty-state"><FileText size={39} strokeWidth={1.3}/><h3>Your first quote starts here.</h3><p>Save your progress and pick it up anytime.</p></div> : <div className="quote-list">{[...quotes].sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)).map(quote => <button key={quote.id} className="quote-row" onClick={() => resume(quote.id)}><div><span className="quote-status">{quote.approvedAt ? 'APPROVED' : 'DRAFT'} · {jobNames[quote.type]}</span><h3>{String(quote.answers.title || 'Untitled quote')}</h3><p>{String(quote.answers.customer || 'Customer not added')}</p><small>{new Date(quote.updatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}{quote.lines.length > 0 ? ` · ${money(totals(quote.lines, quote.pricing).total)}` : ' · Scope in progress'}</small></div><ArrowUpRight size={19}/></button>)}</div>}<p className="local-caption">Stored on this device. Export a backup from settings.</p></section></main><Footer next={() => start(selected)} label="Start quote"/></>;
}
