import PortalApproval from './PortalApproval';
import { useState } from 'react';
import { CheckCircle2, CircleAlert, Download, Printer, PencilLine, MapPinned } from 'lucide-react';
import { Stepper } from './components';
import { answerText, derivedTitle, issues, jobNames, money, questions, totals } from './domain';
import type { Quote } from './domain';
import { download } from './storage';
export default function Review({ quote, update, edit, home, remove }: { quote: Quote; update: (patch: Partial<Quote>, approval?: boolean) => void; edit: (stage: 'guide' | 'pricing') => void; home: () => void; remove: () => void }) {
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [message, setMessage] = useState('');
  const unresolved = issues(quote);
  const t = totals(quote.lines, quote.pricing);
  const priceProblems = !quote.lines.length || quote.lines.some(l => !l.description.trim() || !Number.isFinite(l.quantity) || l.quantity <= 0 || [l.material,l.hours,l.rate].some(n => !Number.isFinite(n) || n < 0) || l.quantity * l.material + l.hours * l.rate <= 0 || (l.hours > 0 && l.rate <= 0));
  const canApprove = quote.acknowledged && !priceProblems && (quote.kind === 'estimate' || !unresolved.length);
  const activeQuestions = questions(quote.type, quote.answers).filter(q => !['customer','address','title','contact'].includes(q.id));
  const exportQuote = () => download(`revive-quote-${quote.id.slice(0,8)}.json`, JSON.stringify({ version: 1, quote, calculatedTotals: t }, null, 2));
  return <main className="review-page"><div className="no-print"><Stepper stage="review"/><div className="page-heading"><div><h1>A final look before it goes out.</h1><p>Check the scope, assumptions and price. You’re in control.</p></div><button className="secondary" onClick={() => edit('pricing')}><PencilLine size={16}/>Edit pricing</button></div>
    {quote.approvedAt ? <div className="success-banner"><CheckCircle2 size={21}/><p>Approved on {new Date(quote.approvedAt).toLocaleString()}. Any edits will return this quote to draft. Nothing has been sent to the customer.</p></div> : <div className="info-banner"><CircleAlert size={20}/><p>{priceProblems ? 'Some lines still need quantities or pricing. Complete them before approving.' : 'Review and acknowledge the scope and pricing below before approving.'}</p></div>}
    {unresolved.length > 0 && <details className="issues" open><summary>{unresolved.length} item{unresolved.length === 1 ? '' : 's'} to review</summary><ul>{unresolved.map((issue,i) => <li key={i}>{issue}</li>)}</ul><p>Unknowns stay visible in the customer document. Resolve all flagged items before approving a fixed quote.</p></details>}
  </div><div className="review-layout"><article className="quote-document" aria-label="Customer quote preview"><div className="document-heading"><img src="/revive-logo.png" alt="Revive Repair Specialists"/><div><span>{quote.approvedAt ? 'APPROVED' : 'DRAFT'}</span><h2>{quote.kind === 'fixed' ? 'Fixed quote' : 'Preliminary estimate'}</h2><small>REF {quote.id.slice(0,8).toUpperCase()} · {new Date(quote.createdAt).toLocaleDateString()}</small></div></div><div className="document-client"><div><small>PREPARED FOR</small><h3>{answerText(quote.answers, 'customer')}</h3><p>{answerText(quote.answers, 'contact')}</p></div><div><small>JOB LOCATION</small><p>{answerText(quote.answers, 'address')}</p></div></div><h2>{derivedTitle(quote)}</h2><p className="document-type">{jobNames[quote.type]}</p><div className="document-scope"><h3>Scope & job details</h3>{activeQuestions.map(question => { const a = quote.answers[question.id]; if (!a || (Array.isArray(a) && !a.length)) return null; return <div key={question.id}><strong>{question.title}</strong><p>{Array.isArray(a) ? a.join(', ') : a}{question.type === 'number' && a !== 'Not sure yet' ? ` ${question.unit ?? ''}` : ''}</p></div>; })}</div><h3>Pricing</h3><div className="customer-lines">{quote.lines.map(l => <div key={l.id}><span>{l.description || 'Unnamed item'}<small>{l.quantity} {l.unit}{l.quantity !== 1 && l.unit === 'allowance' ? 's' : ''}</small></span><strong>{money(l.quantity * l.material + l.hours * l.rate)}</strong></div>)}</div><dl className="totals document-totals"><div><dt>Direct costs</dt><dd>{money(t.direct)}</dd></div><div><dt>Contingency ({quote.pricing.contingency}%)</dt><dd>{money(t.contingency)}</dd></div><div><dt>Markup ({quote.pricing.markup}%)</dt><dd>{money(t.markup)}</dd></div><div><dt>Project Fee (10%)</dt><dd>{money(t.fee)}</dd></div><div><dt>Tax ({quote.pricing.tax}%)</dt><dd>{money(t.tax)}</dd></div><div className="grand-total"><dt>Total</dt><dd>{money(t.total)}</dd></div></dl>
    {unresolved.length > 0 && <section className="document-warning"><h3>Items pending confirmation</h3><ul>{unresolved.map((item, i) => <li key={i}>{item}</li>)}</ul></section>}
    {[['Assumptions',quote.assumptions],['Exclusions',quote.exclusions],['Terms & validity',quote.terms]].map(([label,value]) => value.trim() ? <section key={label} className="document-text"><h3>{label}</h3><p>{value}</p></section> : null)}<p className="document-footnote">{quote.kind === 'estimate' ? 'Preliminary estimate. Price and scope are subject to confirmation of the information and assumptions above.' : 'Fixed price for the scope and terms stated above. Work outside this scope requires a separately agreed change.'}{!quote.approvedAt && ' DRAFT — not approved for issue.'}</p></article>
    <aside className="review-controls no-print"><h2>Make it clear.</h2><label className="field"><span>Quote type</span><select value={quote.kind} onChange={e => update({ kind: e.target.value as Quote['kind'] })}><option value="estimate">Preliminary estimate</option><option value="fixed">Fixed quote</option></select></label><p className="fine-print">Phone-created quotes can be fixed. Complete the scope, pricing and terms before approval.</p>{(['assumptions','exclusions','terms'] as const).map(field => <label className="field" key={field}><span>{field === 'terms' ? 'Terms, payment & validity' : field.charAt(0).toUpperCase() + field.slice(1)}</span><textarea rows={3} value={quote[field]} onChange={e => update({ [field]: e.target.value })} placeholder={field === 'exclusions' ? 'State what is excluded, or explicitly state none.' : field === 'terms' ? 'Payment schedule, quote validity, warranty…' : 'Record allowances and assumptions for the customer.'}/></label>)}<button className="text-button" onClick={() => edit('guide')}>Review or edit job answers</button><label className="acknowledge"><input type="checkbox" checked={quote.acknowledged} onChange={e => update({ acknowledged: e.target.checked })}/><span>I have reviewed the scope, quantities, rates, tax treatment and all flagged assumptions.</span></label><PortalApproval quote={quote} canApprove={canApprove} update={update}/><button className="secondary full" disabled={!canApprove || !!quote.approvedAt} onClick={() => { update({ approvedAt: new Date().toISOString() }, true); setMessage('Quote approved on this device. Nothing has been sent to the customer.'); }}><CheckCircle2 size={18}/>{quote.approvedAt ? 'Quote approved' : 'Approve on this device only'}</button><button className="secondary full" onClick={() => window.print()}><Printer size={18}/>{quote.approvedAt ? 'Print / save PDF' : 'Print draft / save PDF'}</button><button className="secondary full" onClick={exportQuote}><Download size={18}/>Export quote data</button><p className="fine-print">Use your browser’s “Save as PDF” printer. Turn off browser headers and footers for a clean document.</p><div className="connection-status"><MapPinned size={18}/><p>Email and text delivery are not connected. Portal saving is a separate action above. Exporting or printing does not send this quote.</p></div><button className="secondary full" onClick={home}>Back to all quotes</button>{message && <p role="status" className="success-text">{message}</p>}<div className="delete-quote">{confirmDelete ? <><p>Delete this quote from this device? This cannot be undone.</p><button className="danger" onClick={remove}>Delete quote permanently</button><button className="text-button" onClick={() => setConfirmDelete(false)}>Keep quote</button></> : <button className="text-button muted" onClick={() => setConfirmDelete(true)}>Delete this quote</button>}</div></aside></div></main>;
}
