import PortalConnection from './PortalConnection';
import { ArrowLeft, Download, MapPinned, Sparkles, Mail, CheckCircle2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { NumberField } from './components';
import type { Pricing } from './domain';
export default function Settings({ pricing, change, back, backup }: { pricing: Pricing; change: (p: Pricing) => void; back: () => void; backup: () => void }) {
  const [status,setStatus]=useState('Checking connection…');
  useEffect(()=>{const c=new AbortController();fetch('/api/ai/status',{signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>setStatus(d.configured?'Connected · web research enabled':'Key not configured')).catch(()=>{if(!c.signal.aborted)setStatus('Estimate server unavailable');});return()=>c.abort();},[]);
  return <main className="settings-page"><button className="text-button" onClick={back}><ArrowLeft size={17}/>Back</button><h1>Pricing & connections</h1><p className="lead">Set your starting point. Stay in control of every quote.</p><div className="settings-grid"><section className="settings-card"><h2>Default pricing</h2><p>Used for new quotes. Existing quotes keep their own rates.</p><NumberField label="Default labor rate" value={pricing.laborRate} suffix="$/hr" change={n => change({ ...pricing, laborRate: n })}/><NumberField label="Default markup" value={pricing.markup} suffix="%" max={1000} change={n => change({ ...pricing, markup: n })}/><NumberField label="Default contingency" value={pricing.contingency} suffix="%" max={100} change={n => change({ ...pricing, contingency: n })}/><NumberField label="Default tax on material / subcontract" value={pricing.tax} suffix="%" max={100} change={n => change({ ...pricing, tax: n })}/><p className="fine-print">15% markup is the editable starting value from the previous estimate approach. Other rates start at zero so nothing is assumed.</p><span className="settings-saved"><CheckCircle2 size={15}/>Changes save automatically when device storage is available</span></section><section className="settings-card"><h2>Connected services</h2><p>AI research and estimating are connected through the local server. Other services are listed below.</p><div className="service"><MapPinned/><div><h3>Automatic roof measurement</h3><span>Not connected</span><p>Look up the address, confirm the building, review roof sections, area, pitch and imagery date. Manual surface or footprint measurements are available in the roofing guide.</p><small>Requires Google Maps and Solar API setup plus a private server integration.</small></div></div><div className="service"><Sparkles/><div><h3>AI scope & local pricing</h3><span>{status}</span><p>Build estimate researches local-first material sources and relevant project costs, then prepares an editable priced proposal. Review cited prices, allowances and assumptions before approval. API usage is billed to your OpenAI account.</p></div></div><PortalConnection/><div className="service"><Mail/><div><h3>Email & text delivery</h3><span>Not connected</span><p>Recipient confirmation and delivery records will be added with the messaging connection. You can print or export quotes now.</p></div></div></section><section className="settings-card"><h2>Your data</h2><p>Drafts are stored in this browser. Approved revisions saved successfully to the portal remain there; unsynced drafts do not appear on another device. Keep a backup of important work.</p><button className="secondary" onClick={backup}><Download size={18}/>Export all quote data</button><p className="fine-print">Exports contain customer information and quote details. Keep them somewhere appropriate. This version exports backups; restoring and shared account storage are planned.</p></section></div></main>;
}
